name: Release and publish packages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    needs:
      - dependencies

    uses: ./.github/workflows/_validation.reusable.yml
  #    with:
  #      cache-path: ${{ needs.dependencies.outputs.pnpm_cache_path }}
  #      cache-key: ${{ needs.dependencies.outputs.pnpm_cache_key }}
  #      node-version: ${{ needs.dependencies.outputs.node-version }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - validation

    steps:
      - name: Checkout client-application repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Get to target release structure | Add readme, license and package files
        run: |
          mkdir dist/esm-release
          mkdir dist/cjs-release
          mv README.md dist/whitelist/
          mv LICENSE.md dist/whitelist/
  #         mv package.json dist/whitelist/ TODO Edit main for entrypoint
  #         mv lib/esm/ dist/whitelist/assets/data/

  #      - name: Upload build artifact
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: build
  #          path: dist

  #      TODO x2
  #      - name: Zip release
  #        run: zip -r release.zip dist/whitelist/
  #
  #      - name: Publish release on github
  #        uses: softprops/action-gh-release@v1
  #        with:
  #          files: release.zip

  publish:
    name: Publish on npm
    runs-on: ubuntu-latest
    needs:
      - release

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: https://registry.npmjs.org
      #          scope: '@gouvfr-anct'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: release

      - name: Publish on npm
        run: |
          cd release/whitelist/
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
